version: "3.8"
services:
    mysql_db:
        image: mysql
        restart: always
        container_name: nodejs_api_mysql
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=superSecret03
        networks:
          - nodejs_api_mysql_network
    adminer:
        image: adminer
        container_name: nodejd_api_mysql_adminer
        restart: always
        ports:
            - 8081:8080
        networks:
          - nodejs_api_mysql_network

networks: 
  nodejs_api_mysql_network:
    driver: bridge
